language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t stoptime9/docker-react -f Dockerfile.dev .

# CI needed for how the Jest library works with Create React App
script:
  - docker run -e CI=true stoptime9/docker-react yarn test

deploy: 
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-837175974840"
  bucket_path: "docker-react"
  on:
    branch: master

access_key_id:
  secure: "$AWS_ACCESS_KEY"
secret_access_key:
  secure: "$AWS_SECRET_KEY"